#!/usr/bin/env python3
"""Bounded, deterministic school events for the Shiomi World.

This module is a small World-fact layer.  Events are derived from a bounded
date rule and a durable feature epoch; they are not generated by an LLM and
do not create actions, Timeline processes, Experience, Memory, or messages.
The only durable event-layer state is the epoch that prevents activation from
backfilling earlier school days.
"""

from __future__ import annotations

import hashlib
import json
import os
import tempfile
from collections.abc import Iterable, Mapping, Sequence
from contextlib import contextmanager
from datetime import date, datetime, time, timezone
from pathlib import Path
from typing import Any, Optional
from zoneinfo import ZoneInfo, ZoneInfoNotFoundError

try:
    import fcntl
except ImportError:  # pragma: no cover - production is POSIX
    fcntl = None

import world_school_day as school_day


FEATURE_ENV = "CHIYO_WORLD_SCHOOL_EVENTS_V1_ENABLED"
WORLD_ID = school_day.WORLD_ID
WORLD_TIMEZONE = school_day.WORLD_TIMEZONE
SCHEMA_VERSION = "world.school.events.v1"
STATE_SCHEMA_VERSION = "world.school.events.state.v1"
PROJECTION_KIND = "shiomi_school_events"
STATE_KIND = "shiomi_school_event_continuity"
STATE_FILENAME = "school_event_continuity.json"
SCHOOL_ID = school_day.SCHOOL_ID
SCHOOL_LOCATION_ID = school_day.SCHOOL_LOCATION_ID
CLASSROOM_ID = school_day.CLASSROOM_ID

EVENT_KINDS = frozenset(
    {
        "INSTITUTION_NOTICE",
        "CLASSROOM_CHANGE",
        "TEACHER_EVENT",
        "CLASSMATE_EVENT",
        "CAMPUS_AMBIENT",
        "SCHOOL_SCHEDULE_EXCEPTION",
    }
)
SOURCE_CATEGORIES = frozenset(
    {
        "SCHOOL_INSTITUTION",
        "TEACHER",
        "NPC",
        "ENVIRONMENT",
        "SCHEDULE_AUTHORITY",
        "UNKNOWN",
    }
)
VISIBILITIES = frozenset({"school_public", "class_public", "location_public"})
EXPOSURE_STATUSES = frozenset(
    {"NOT_EXPOSED", "EXPOSURE_POSSIBLE", "OBSERVED", "REPORTED_LATER", "UNKNOWN"}
)
MAX_EVENTS_PER_DAY = 2
MAX_PARTICIPANTS = 8
MAX_FACT_KEYS = 8
MAX_TEXT_LENGTH = 240
MAX_STATE_BYTES = 4_000
MAX_PROJECTION_BYTES = 12_000

_STATE_KEYS = frozenset(
    {"kind", "schema_version", "world_id", "revision", "continuity_started_at"}
)
_EVENT_KEYS = frozenset(
    {
        "event_id",
        "school_day_id",
        "event_kind",
        "occurred_at",
        "interval",
        "location",
        "source_category",
        "source_actor",
        "participants",
        "visibility",
        "provenance",
        "revision",
        "facts",
    }
)
_INTERVAL_KEYS = frozenset({"starts_at", "ends_at"})
_LOCATION_KEYS = frozenset({"location_id", "area_id"})
_FORBIDDEN_KEYS = frozenset(
    {
        "action",
        "candidate",
        "completion",
        "desire",
        "emotion",
        "goal",
        "importance",
        "kpi",
        "penalty",
        "priority",
        "quest",
        "recommendation",
        "reward",
        "score",
        "todo",
        "wake",
    }
)
_EFFECTS = frozenset(
    {
        "FACILITY_TEMPORARILY_CLOSED",
        "NOTICE_POSTED",
        "PERIOD_CANCELLED",
        "PUBLIC_ITEM_PRESENT",
        "ROOM_CHANGE",
        "TEACHER_SUBSTITUTION",
        "ASSIGNMENT_ISSUED",
    }
)
_EFFECT_REQUIRED_SOURCE = {
    "INSTITUTION_NOTICE": ("SCHOOL_INSTITUTION", "NOTICE_POSTED"),
    "CLASSROOM_CHANGE": ("SCHEDULE_AUTHORITY", "ROOM_CHANGE"),
    "TEACHER_EVENT": ("TEACHER", "TEACHER_SUBSTITUTION"),
    "CLASSMATE_EVENT": ("NPC", "PUBLIC_ITEM_PRESENT"),
    "CAMPUS_AMBIENT": ("ENVIRONMENT", "FACILITY_TEMPORARILY_CLOSED"),
    "SCHOOL_SCHEDULE_EXCEPTION": ("SCHEDULE_AUTHORITY", "PERIOD_CANCELLED"),
}
_EFFECTIVE_CLASSROOM_IDS = frozenset(
    {"school.classroom.room_a", "school.classroom.room_b", "school.classroom.room_c"}
)
_TRUE_VALUES = frozenset({"1", "true", "yes", "on"})


class SchoolEventsError(ValueError):
    """Raised when a bounded school-event contract is malformed."""


def _copy_json(value: Any, *, maximum: int = MAX_PROJECTION_BYTES) -> Any:
    try:
        encoded = json.dumps(
            value,
            ensure_ascii=False,
            sort_keys=True,
            separators=(",", ":"),
            allow_nan=False,
        ).encode("utf-8")
    except (TypeError, ValueError) as exc:
        raise SchoolEventsError("value is not bounded JSON") from exc
    if len(encoded) > maximum:
        raise SchoolEventsError("value exceeds bounded JSON size")
    return json.loads(encoded)


def _environment(environment: Optional[Mapping[str, str]]) -> Mapping[str, str]:
    return os.environ if environment is None else environment


def _truthy(value: Any) -> bool:
    return str(value or "").strip().lower() in _TRUE_VALUES


def feature_enabled(environment: Optional[Mapping[str, str]] = None) -> bool:
    return _truthy(_environment(environment).get(FEATURE_ENV))


def _zone() -> ZoneInfo:
    try:
        return ZoneInfo(WORLD_TIMEZONE)
    except ZoneInfoNotFoundError as exc:  # pragma: no cover - platform data
        raise SchoolEventsError("school timezone is unavailable") from exc


def _local(now: Optional[datetime]) -> datetime:
    instant = datetime.now(timezone.utc) if now is None else now
    if not isinstance(instant, datetime) or instant.tzinfo is None or instant.utcoffset() is None:
        raise SchoolEventsError("now must be timezone-aware")
    return instant.astimezone(_zone())


def _timestamp(value: Any, field: str) -> str:
    if isinstance(value, datetime):
        instant = value
    elif isinstance(value, str):
        text = value.strip()
        if text.endswith(("Z", "z")):
            text = text[:-1] + "+00:00"
        try:
            instant = datetime.fromisoformat(text)
        except ValueError as exc:
            raise SchoolEventsError(f"{field} must be ISO datetime") from exc
    else:
        raise SchoolEventsError(f"{field} must be ISO datetime")
    if instant.tzinfo is None or instant.utcoffset() is None:
        raise SchoolEventsError(f"{field} must include timezone")
    return instant.astimezone(timezone.utc).isoformat(timespec="seconds").replace(
        "+00:00", "Z"
    )


def _instant(value: Any, field: str = "timestamp") -> datetime:
    return datetime.fromisoformat(_timestamp(value, field).replace("Z", "+00:00"))


def _text(value: Any, field: str, maximum: int = MAX_TEXT_LENGTH) -> str:
    if not isinstance(value, str):
        raise SchoolEventsError(f"{field} must be a string")
    result = value.strip()
    if not result or len(result) > maximum or any(char in result for char in "\r\n\x00"):
        raise SchoolEventsError(f"{field} is invalid")
    return result


def _id(value: Any, field: str) -> str:
    result = _text(value, field, 160)
    if any(char.isspace() for char in result):
        raise SchoolEventsError(f"{field} must not contain whitespace")
    return result


def _revision(value: Any, field: str) -> int:
    if isinstance(value, bool) or not isinstance(value, int) or value < 0:
        raise SchoolEventsError(f"{field} must be a non-negative integer")
    return value


def _forbidden_key(key: Any) -> bool:
    if not isinstance(key, str):
        return True
    normalized = key.strip().lower()
    return normalized in _FORBIDDEN_KEYS or normalized.split("_", 1)[0] in _FORBIDDEN_KEYS


def _bounded_facts(value: Any) -> dict[str, Any]:
    if not isinstance(value, Mapping) or not value or len(value) > MAX_FACT_KEYS:
        raise SchoolEventsError("facts must be a small object")
    if any(_forbidden_key(key) for key in value):
        raise SchoolEventsError("facts contain a forbidden authority field")
    normalized = _copy_json(dict(value), maximum=2_000)
    if not isinstance(normalized, dict):
        raise SchoolEventsError("facts are invalid")
    effect = normalized.get("effect")
    if effect not in _EFFECTS:
        raise SchoolEventsError("facts.effect is unsupported")
    if normalized.get("period_id") is not None:
        _id(normalized["period_id"], "facts.period_id")
    if normalized.get("effective_location_id") is not None:
        if normalized["effective_location_id"] not in _EFFECTIVE_CLASSROOM_IDS:
            raise SchoolEventsError("facts.effective_location_id is invalid")
    return normalized


def _school_day_id(local_date: date) -> str:
    return f"{SCHOOL_ID}:{local_date.isoformat()}"


def _location(value: Any) -> dict[str, str]:
    if not isinstance(value, Mapping) or set(value) != _LOCATION_KEYS:
        raise SchoolEventsError("event location is invalid")
    location_id = _id(value.get("location_id"), "location.location_id")
    area_id = _id(value.get("area_id"), "location.area_id")
    if location_id != SCHOOL_LOCATION_ID or area_id != SCHOOL_LOCATION_ID:
        raise SchoolEventsError("school event location is outside the school")
    return {"location_id": location_id, "area_id": area_id}


def _participants(value: Any) -> list[str]:
    if not isinstance(value, list) or len(value) > MAX_PARTICIPANTS:
        raise SchoolEventsError("participants are invalid")
    result = [_id(item, "participant") for item in value]
    if len(result) != len(set(result)):
        raise SchoolEventsError("participants must be unique")
    return result


def validate_event(value: Any) -> dict[str, Any]:
    """Validate one immutable factual event record."""

    if not isinstance(value, Mapping) or set(value) != _EVENT_KEYS:
        raise SchoolEventsError("event has an invalid schema")
    event_id = _id(value.get("event_id"), "event_id")
    school_day_id = _id(value.get("school_day_id"), "school_day_id")
    if not school_day_id.startswith(f"{SCHOOL_ID}:"):
        raise SchoolEventsError("school_day_id is not canonical")
    event_kind = _text(value.get("event_kind"), "event_kind", 64).upper()
    if event_kind not in EVENT_KINDS:
        raise SchoolEventsError("event_kind is unsupported")
    occurred_at = _timestamp(value.get("occurred_at"), "occurred_at")
    interval = value.get("interval")
    if not isinstance(interval, Mapping) or set(interval) != _INTERVAL_KEYS:
        raise SchoolEventsError("event interval is invalid")
    starts_at = _timestamp(interval.get("starts_at"), "interval.starts_at")
    ends_at = _timestamp(interval.get("ends_at"), "interval.ends_at")
    if not _instant(starts_at) < _instant(ends_at):
        raise SchoolEventsError("event interval is not ordered")
    occurred = _instant(occurred_at)
    if not _instant(starts_at) <= occurred < _instant(ends_at):
        raise SchoolEventsError("occurred_at is outside event interval")
    location = _location(value.get("location"))
    source_category = _text(value.get("source_category"), "source_category", 48).upper()
    if source_category not in SOURCE_CATEGORIES:
        raise SchoolEventsError("source_category is unsupported")
    source_actor = value.get("source_actor")
    if source_actor is not None:
        source_actor = _id(source_actor, "source_actor")
    if source_category == "UNKNOWN" and source_actor is not None:
        raise SchoolEventsError("UNKNOWN source cannot identify an actor")
    participants = _participants(value.get("participants"))
    visibility = _text(value.get("visibility"), "visibility", 32)
    if visibility not in VISIBILITIES:
        raise SchoolEventsError("visibility is unsupported")
    provenance = value.get("provenance")
    if not isinstance(provenance, Mapping) or set(provenance) != {"kind", "source", "factual"}:
        raise SchoolEventsError("provenance is invalid")
    if not all(isinstance(provenance.get(key), str) and provenance[key].strip() for key in ("kind", "source")):
        raise SchoolEventsError("provenance identity is invalid")
    if provenance.get("factual") is not True:
        raise SchoolEventsError("event provenance must be factual")
    revision = _revision(value.get("revision"), "revision")
    facts = _bounded_facts(value.get("facts"))
    expected_source, expected_effect = _EFFECT_REQUIRED_SOURCE[event_kind]
    valid_effect = facts.get("effect") == expected_effect
    if event_kind == "TEACHER_EVENT":
        valid_effect = facts.get("effect") in {
            "TEACHER_SUBSTITUTION",
            "ASSIGNMENT_ISSUED",
        }
    if source_category != expected_source or not valid_effect:
        raise SchoolEventsError("event source/effect do not match event kind")
    if event_kind in {"CLASSROOM_CHANGE", "SCHOOL_SCHEDULE_EXCEPTION", "TEACHER_EVENT"}:
        if not isinstance(facts.get("period_id"), str) or not facts["period_id"].strip():
            raise SchoolEventsError("period-bound event lacks period_id")
    if event_kind == "CLASSROOM_CHANGE" and facts.get("effective_location_id") is None:
        raise SchoolEventsError("classroom change lacks effective location")
    if event_kind == "CLASSMATE_EVENT" and source_actor is None:
        raise SchoolEventsError("classmate event lacks bounded source actor")
    return _copy_json(
        {
            "event_id": event_id,
            "school_day_id": school_day_id,
            "event_kind": event_kind,
            "occurred_at": occurred_at,
            "interval": {"starts_at": starts_at, "ends_at": ends_at},
            "location": location,
            "source_category": source_category,
            "source_actor": source_actor,
            "participants": participants,
            "visibility": visibility,
            "provenance": {
                "kind": str(provenance["kind"]).strip(),
                "source": str(provenance["source"]).strip(),
                "factual": True,
            },
            "revision": revision,
            "facts": facts,
        }
    )


def event_id_for(
    school_day_id: Any,
    event_kind: Any,
    *,
    slot: Any,
) -> str:
    identity = {
        "school_day_id": _id(school_day_id, "school_day_id"),
        "event_kind": _text(event_kind, "event_kind", 64).upper(),
        "slot": _id(slot, "slot"),
    }
    if identity["event_kind"] not in EVENT_KINDS:
        raise SchoolEventsError("event_kind is unsupported")
    payload = json.dumps(identity, ensure_ascii=False, sort_keys=True, separators=(",", ":"))
    return "school-event-" + hashlib.sha256(payload.encode("utf-8")).hexdigest()


def _period_window(local_date: date, period_id: str) -> tuple[int, int]:
    for item in school_day.TIMETABLE:
        if item.period == period_id:
            return item.start_minute, item.end_minute
    raise SchoolEventsError("period_id is not a class period")


def _at(local_date: date, minute: int) -> datetime:
    if isinstance(minute, bool) or not isinstance(minute, int) or not 0 <= minute < 24 * 60:
        raise SchoolEventsError("event minute is invalid")
    return datetime.combine(
        local_date,
        time(minute // 60, minute % 60),
        tzinfo=_zone(),
    )


def _default_specs(local_date: date) -> tuple[dict[str, Any], ...]:
    if not school_day.is_school_day(local_date):
        return ()
    # The rule is intentionally sparse: six event days in a fourteen-day
    # cycle and no event on the other days.  It is not a daily minimum.
    slot = local_date.toordinal() % 14
    if slot in {0, 2, 4, 6, 8, 12, 13}:
        return ()
    if slot == 1:
        return (
            {
                "event_kind": "INSTITUTION_NOTICE",
                "source_category": "SCHOOL_INSTITUTION",
                "source_actor": "school_office",
                "visibility": "school_public",
                "start_minute": 8 * 60,
                "end_minute": 18 * 60,
                "facts": {"effect": "NOTICE_POSTED", "notice_type": "school_notice"},
                "slot": "notice",
            },
        )
    if slot == 3:
        return (
            {
                "event_kind": "CLASSROOM_CHANGE",
                "source_category": "SCHEDULE_AUTHORITY",
                "source_actor": "school_schedule",
                "visibility": "class_public",
                "period_id": "morning_class_1",
                "facts": {
                    "effect": "ROOM_CHANGE",
                    "period_id": "morning_class_1",
                    "effective_location_id": "school.classroom.room_b",
                },
                "slot": "room-change",
            },
        )
    if slot == 5:
        return (
            {
                "event_kind": "TEACHER_EVENT",
                "source_category": "TEACHER",
                "source_actor": "teacher:substitute",
                "visibility": "class_public",
                "period_id": "afternoon_class_1",
                "facts": {
                    "effect": "TEACHER_SUBSTITUTION",
                    "period_id": "afternoon_class_1",
                },
                "slot": "teacher-event",
            },
        )
    if slot == 10:
        return (
            {
                "event_kind": "CLASSMATE_EVENT",
                "source_category": "NPC",
                "source_actor": "npc:shiomi_npc_mio_shiraishi",
                "participants": ["npc:shiomi_npc_mio_shiraishi"],
                "visibility": "class_public",
                "period_id": "lunch",
                "facts": {"effect": "PUBLIC_ITEM_PRESENT", "item_reference": "book"},
                "slot": "classmate-event",
            },
        )
    if slot == 11:
        return (
            {
                "event_kind": "SCHOOL_SCHEDULE_EXCEPTION",
                "source_category": "SCHEDULE_AUTHORITY",
                "source_actor": "school_schedule",
                "visibility": "class_public",
                "period_id": "morning_class_2",
                "facts": {
                    "effect": "PERIOD_CANCELLED",
                    "period_id": "morning_class_2",
                },
                "slot": "cancelled-period",
            },
        )
    if slot == 9:
        return (
            {
                "event_kind": "CAMPUS_AMBIENT",
                "source_category": "ENVIRONMENT",
                "visibility": "location_public",
                "start_minute": 11 * 60,
                "end_minute": 12 * 60,
                "facts": {
                    "effect": "FACILITY_TEMPORARILY_CLOSED",
                    "facility_id": "school_library",
                },
                "slot": "campus-ambient",
            },
        )
    return ()


def _normalized_specs(
    local_date: date,
    event_specs: Optional[Iterable[Mapping[str, Any]]],
) -> tuple[Mapping[str, Any], ...]:
    if event_specs is None:
        return _default_specs(local_date)
    if isinstance(event_specs, (str, bytes)):
        raise SchoolEventsError("event_specs must be an iterable of objects")
    specs = tuple(event_specs)
    if len(specs) > MAX_EVENTS_PER_DAY:
        raise SchoolEventsError("daily event bound exceeded")
    return specs


def _build_event(local_date: date, spec: Mapping[str, Any]) -> dict[str, Any]:
    if not isinstance(spec, Mapping):
        raise SchoolEventsError("event spec is invalid")
    event_kind = _text(spec.get("event_kind"), "event_kind", 64).upper()
    if event_kind not in EVENT_KINDS:
        raise SchoolEventsError("event_kind is unsupported")
    facts = _bounded_facts(spec.get("facts"))
    period_id = facts.get("period_id") or spec.get("period_id")
    if period_id is not None and facts.get("period_id") is None:
        period_id = _id(period_id, "period_id")
        facts["period_id"] = period_id
    if period_id is not None:
        start_minute, end_minute = _period_window(local_date, period_id)
    else:
        start_minute = spec.get("start_minute")
        end_minute = spec.get("end_minute")
    if isinstance(start_minute, bool) or not isinstance(start_minute, int):
        raise SchoolEventsError("start_minute is invalid")
    if isinstance(end_minute, bool) or not isinstance(end_minute, int):
        raise SchoolEventsError("end_minute is invalid")
    starts_at = _at(local_date, start_minute)
    ends_at = _at(local_date, end_minute)
    if starts_at >= ends_at:
        raise SchoolEventsError("event window is invalid")
    school_day_id = _school_day_id(local_date)
    slot = _id(spec.get("slot"), "slot")
    event = {
        "event_id": event_id_for(school_day_id, event_kind, slot=slot),
        "school_day_id": school_day_id,
        "event_kind": event_kind,
        "occurred_at": starts_at,
        "interval": {"starts_at": starts_at, "ends_at": ends_at},
        "location": {"location_id": SCHOOL_LOCATION_ID, "area_id": SCHOOL_LOCATION_ID},
        "source_category": _text(spec.get("source_category"), "source_category", 48).upper(),
        "source_actor": spec.get("source_actor"),
        "participants": spec.get("participants", []),
        "visibility": spec.get("visibility"),
        "provenance": {
            "kind": "deterministic_school_rule",
            "source": "shiomi_school_event_layer_v1",
            "factual": True,
        },
        "revision": 1,
        "facts": facts,
    }
    return validate_event(event)


def _epoch_instant(continuity_started_at: Any, local_date: date) -> datetime:
    if continuity_started_at is None:
        return datetime.combine(local_date, time.min, tzinfo=_zone()).astimezone(timezone.utc)
    return _instant(continuity_started_at, "continuity_started_at")


def materialize_school_events(
    local_date: date,
    *,
    continuity_started_at: Optional[datetime | str] = None,
    event_specs: Optional[Iterable[Mapping[str, Any]]] = None,
) -> list[dict[str, Any]]:
    """Derive a stable bounded event set for one school-local date.

    ``event_specs`` is an injected deterministic fixture seam; production
    observation uses only the built-in bounded rule.
    """

    if isinstance(local_date, datetime) or not isinstance(local_date, date):
        raise SchoolEventsError("local_date must be a date")
    if not school_day.is_school_day(local_date):
        return []
    epoch = _epoch_instant(continuity_started_at, local_date)
    events = []
    for spec in _normalized_specs(local_date, event_specs):
        event = _build_event(local_date, spec)
        if _instant(event["occurred_at"]) < epoch:
            continue
        events.append(event)
    if len(events) > MAX_EVENTS_PER_DAY:
        raise SchoolEventsError("daily event bound exceeded")
    return _copy_json(events)


def _home(hermes_home: Optional[Path | str] = None) -> Path:
    raw = hermes_home if hermes_home is not None else os.environ.get("HERMES_HOME")
    path = Path(raw).expanduser() if raw else Path.home() / ".hermes"
    if not path.is_absolute():
        raise SchoolEventsError("hermes_home must be absolute")
    return path


def state_path(hermes_home: Optional[Path | str] = None) -> Path:
    return _home(hermes_home) / "data" / "world" / STATE_FILENAME


def _validate_state(value: Any) -> dict[str, Any]:
    if not isinstance(value, Mapping) or set(value) != _STATE_KEYS:
        raise SchoolEventsError("event continuity state has invalid fields")
    if value.get("kind") != STATE_KIND or value.get("schema_version") != STATE_SCHEMA_VERSION:
        raise SchoolEventsError("event continuity state identity is invalid")
    if value.get("world_id") != WORLD_ID:
        raise SchoolEventsError("event continuity state world is invalid")
    revision = _revision(value.get("revision"), "revision")
    started = _timestamp(value.get("continuity_started_at"), "continuity_started_at")
    return {
        "kind": STATE_KIND,
        "schema_version": STATE_SCHEMA_VERSION,
        "world_id": WORLD_ID,
        "revision": revision,
        "continuity_started_at": started,
    }


def load_state(hermes_home: Optional[Path | str] = None) -> Optional[dict[str, Any]]:
    path = state_path(hermes_home)
    try:
        return _validate_state(json.loads(path.read_text(encoding="utf-8")))
    except (OSError, TypeError, ValueError, json.JSONDecodeError, SchoolEventsError):
        return None


def _save_state(path: Path, state: Mapping[str, Any]) -> dict[str, Any]:
    normalized = _validate_state(state)
    path.parent.mkdir(parents=True, exist_ok=True)
    payload = json.dumps(normalized, ensure_ascii=False, sort_keys=True, separators=(",", ":")) + "\n"
    if len(payload.encode("utf-8")) > MAX_STATE_BYTES:
        raise SchoolEventsError("event continuity state is too large")
    descriptor, raw_temp = tempfile.mkstemp(prefix=f".{path.name}.", dir=str(path.parent), text=True)
    temporary_path = Path(raw_temp)
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8") as handle:
            handle.write(payload)
            handle.flush()
            os.fsync(handle.fileno())
        os.chmod(temporary_path, 0o600)
        os.replace(temporary_path, path)
    finally:
        if temporary_path.exists():
            temporary_path.unlink()
    return normalized


@contextmanager
def _lock(path: Path):
    if fcntl is None:
        raise SchoolEventsError("event continuity lock unavailable")
    path.parent.mkdir(parents=True, exist_ok=True)
    lock_path = path.with_name(path.name + ".lock")
    with lock_path.open("a+") as handle:
        fcntl.flock(handle.fileno(), fcntl.LOCK_EX)
        try:
            yield
        finally:
            fcntl.flock(handle.fileno(), fcntl.LOCK_UN)


def _ensure_state(home: Path, observed_at: str) -> dict[str, Any]:
    path = state_path(home)
    with _lock(path):
        if path.exists():
            loaded = load_state(home)
            if loaded is None:
                raise SchoolEventsError("event continuity state is corrupt")
            return loaded
        return _save_state(
            path,
            {
                "kind": STATE_KIND,
                "schema_version": STATE_SCHEMA_VERSION,
                "world_id": WORLD_ID,
                "revision": 1,
                "continuity_started_at": observed_at,
            },
        )


def _location_id(value: Any) -> Optional[str]:
    if not isinstance(value, str):
        return None
    normalized = value.strip()
    if not normalized or len(normalized) > 96 or any(char.isspace() for char in normalized):
        return None
    return normalized


def _initial_exposure(event: Mapping[str, Any], current_location_id: Any) -> str:
    location_id = _location_id(current_location_id)
    if location_id in {SCHOOL_LOCATION_ID, CLASSROOM_ID}:
        return "EXPOSURE_POSSIBLE"
    if location_id is None:
        return "UNKNOWN"
    return "NOT_EXPOSED"


def _exposure_records(events: Sequence[Mapping[str, Any]], current_location_id: Any) -> list[dict[str, str]]:
    return [
        {"event_id": str(event["event_id"]), "status": _initial_exposure(event, current_location_id)}
        for event in events
    ]


def _schedule_exceptions(events: Sequence[Mapping[str, Any]]) -> list[dict[str, Any]]:
    result = []
    for event in events:
        facts = event["facts"]
        if facts.get("effect") not in {"PERIOD_CANCELLED", "ROOM_CHANGE"}:
            continue
        item = {
            "event_id": event["event_id"],
            "period_id": facts.get("period_id"),
            "effect": facts["effect"],
        }
        if facts.get("effective_location_id") is not None:
            item["effective_location_id"] = facts["effective_location_id"]
        result.append(item)
    return result


def observe_school_events(
    *,
    hermes_home: Optional[Path | str] = None,
    now: Optional[datetime] = None,
    current_location_id: Any = None,
    environment: Optional[Mapping[str, str]] = None,
    school_day_projection: Optional[Mapping[str, Any]] = None,
) -> dict[str, Any]:
    """Materialize the current school-day facts through a bounded World seam."""

    env = _environment(environment)
    if not feature_enabled(env):
        return {
            "kind": PROJECTION_KIND,
            "schema_version": SCHEMA_VERSION,
            "status": "disabled",
            "reason_code": "FEATURE_DISABLED",
        }
    if not school_day.feature_enabled(env):
        return {
            "kind": PROJECTION_KIND,
            "schema_version": SCHEMA_VERSION,
            "status": "unavailable",
            "reason_code": "SCHOOL_DAY_FEATURE_DISABLED",
        }
    try:
        local = _local(now)
        projection = school_day_projection
        if projection is None:
            projection = school_day.observe_school_day(
                now=local,
                current_location_id=current_location_id,
                environment=env,
            )
        if not isinstance(projection, Mapping) or projection.get("status") != "available":
            return {
                "kind": PROJECTION_KIND,
                "schema_version": SCHEMA_VERSION,
                "status": "unavailable",
                "reason_code": str(projection.get("reason_code") if isinstance(projection, Mapping) else "SCHOOL_DAY_UNAVAILABLE"),
            }
        if not bool(projection.get("school_day")):
            return {
                "kind": PROJECTION_KIND,
                "schema_version": SCHEMA_VERSION,
                "status": "not_school_day",
                "local_date": local.date().isoformat(),
                "events": [],
                "provenance": "shiomi_school_day",
            }
        observed_at = _timestamp(local, "observed_at")
        state = _ensure_state(_home(hermes_home), observed_at)
        epoch = _instant(state["continuity_started_at"], "continuity_started_at")
        if local.astimezone(timezone.utc) < epoch:
            events: list[dict[str, Any]] = []
            status = "before_continuity_epoch"
        else:
            events = materialize_school_events(
                local.date(),
                continuity_started_at=state["continuity_started_at"],
            )
            status = "available"
        result = {
            "kind": PROJECTION_KIND,
            "schema_version": SCHEMA_VERSION,
            "status": status,
            "world_id": WORLD_ID,
            "school_day": {
                "school_day_id": _school_day_id(local.date()),
                "local_date": local.date().isoformat(),
            },
            "continuity_started_at": state["continuity_started_at"],
            "events": events,
            "exposure": _exposure_records(events, current_location_id),
            "schedule_exceptions": _schedule_exceptions(events),
            "knowledge_boundary": {
                "automatic_main_self_projection": False,
                "allowed_statuses": sorted(EXPOSURE_STATUSES),
            },
            "provenance": "shiomi_school_event_layer_v1",
        }
        return _copy_json(result, maximum=MAX_PROJECTION_BYTES)
    except (OSError, SchoolEventsError, TypeError, ValueError):
        return {
            "kind": PROJECTION_KIND,
            "schema_version": SCHEMA_VERSION,
            "status": "unavailable",
            "reason_code": "SCHOOL_EVENTS_UNAVAILABLE",
        }


def attach_exposure(
    projection: Mapping[str, Any],
    school_life_projection: Optional[Mapping[str, Any]],
) -> dict[str, Any]:
    """Attach only exposure eligibility from an existing School Life fact."""

    if not isinstance(projection, Mapping):
        raise SchoolEventsError("projection is invalid")
    result = _copy_json(dict(projection))
    events = result.get("events")
    if not isinstance(events, list):
        raise SchoolEventsError("projection events are invalid")
    for event in events:
        validate_event(event)
    if not isinstance(school_life_projection, Mapping):
        return result
    attendance = {
        item.get("period_id"): item.get("attendance")
        for item in school_life_projection.get("attendance", [])
        if isinstance(item, Mapping)
    }
    presence = school_life_projection.get("presence")
    presence_status = presence.get("status") if isinstance(presence, Mapping) else None
    updated: list[dict[str, str]] = []
    for event in events:
        period_id = event["facts"].get("period_id")
        if period_id is not None and period_id in attendance:
            status = {
                "PRESENT": "EXPOSURE_POSSIBLE",
                "LATE": "EXPOSURE_POSSIBLE",
                "ABSENT": "NOT_EXPOSED",
                "UNKNOWN": "UNKNOWN",
            }.get(attendance[period_id], "UNKNOWN")
        else:
            status = {
                "PRESENT": "EXPOSURE_POSSIBLE",
                "LEFT": "NOT_EXPOSED",
                "NOT_ARRIVED": "NOT_EXPOSED",
                "TRAVEL_PENDING": "UNKNOWN",
                "UNKNOWN": "UNKNOWN",
            }.get(presence_status, "UNKNOWN")
        updated.append({"event_id": event["event_id"], "status": status})
    result["exposure"] = updated
    return _copy_json(result, maximum=MAX_PROJECTION_BYTES)


def effective_class_sessions(
    sessions: Iterable[Mapping[str, Any]],
    school_event_projection: Optional[Mapping[str, Any]],
) -> list[dict[str, Any]]:
    """Apply only explicit room/cancellation facts to a class-session copy."""

    result = _copy_json(list(sessions), maximum=8_000)
    if school_event_projection is None:
        return result
    if not isinstance(school_event_projection, Mapping):
        raise SchoolEventsError("school event projection is invalid")
    events = school_event_projection.get("events")
    if not isinstance(events, list):
        raise SchoolEventsError("school event projection events are invalid")
    by_period = {item.get("period"): item for item in result if isinstance(item, Mapping)}
    for raw_event in events:
        event = validate_event(raw_event)
        facts = event["facts"]
        period_id = facts.get("period_id")
        session = by_period.get(period_id)
        if session is None:
            continue
        if facts.get("effect") == "PERIOD_CANCELLED":
            session["status"] = "cancelled"
        elif facts.get("effect") == "ROOM_CHANGE":
            room = session.get("room")
            if not isinstance(room, Mapping):
                continue
            effective_id = facts.get("effective_location_id")
            session["room"] = {
                **dict(room),
                "subspace_id": effective_id,
                "name": "临时教室",
            }
            session["effective_location_id"] = effective_id
    return _copy_json(result, maximum=8_000)


def project_event_knowledge(
    event: Mapping[str, Any],
    *,
    knowledge_status: str,
    report_source: Optional[str] = None,
) -> dict[str, Any]:
    """Project a fact only after an explicit bounded knowledge seam."""

    normalized = validate_event(event)
    status = _text(knowledge_status, "knowledge_status", 32).upper()
    if status not in EXPOSURE_STATUSES:
        raise SchoolEventsError("knowledge_status is unsupported")
    if status not in {"OBSERVED", "REPORTED_LATER"}:
        return {"status": "no_op", "reason_code": "KNOWLEDGE_NOT_ESTABLISHED"}
    if status == "REPORTED_LATER":
        source = _text(report_source, "report_source", 64) if report_source is not None else ""
        if source not in {"classmate", "teacher", "school_notice", "phone_local_messaging"}:
            return {"status": "no_op", "reason_code": "REPORT_SOURCE_NOT_ALLOWED"}
    return {
        "status": "available",
        "knowledge_status": status,
        "event": {
            "event_id": normalized["event_id"],
            "event_kind": normalized["event_kind"],
            "occurred_at": normalized["occurred_at"],
            "location": normalized["location"],
            "facts": normalized["facts"],
        },
        "provenance": "school_event_knowledge_projection",
    }


__all__ = [
    "CLASSROOM_ID",
    "EVENT_KINDS",
    "EXPOSURE_STATUSES",
    "FEATURE_ENV",
    "MAX_EVENTS_PER_DAY",
    "PROJECTION_KIND",
    "SCHEMA_VERSION",
    "SCHOOL_ID",
    "SCHOOL_LOCATION_ID",
    "SOURCE_CATEGORIES",
    "STATE_FILENAME",
    "SchoolEventsError",
    "attach_exposure",
    "effective_class_sessions",
    "event_id_for",
    "feature_enabled",
    "load_state",
    "materialize_school_events",
    "observe_school_events",
    "project_event_knowledge",
    "state_path",
    "validate_event",
]
